rlarjsdn3/EST-2th-Team2-Project

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, README.md, Retrospective/Retrospective.xcodeproj/project.pbxproj, Retrospective/Retrospective.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Retrospective/Retrospective/Core/Extensions/Color+RawRepresentable.swift, Retrospective/Retrospective/Core/Modifiers/DefaultShadow+Modifier.swift, Retrospective/Retrospective/Core/Representable/UIViewRepresentableWrapper.swift, Retrospective/Retrospective/Core/Resources/AppColors.swift, Retrospective/Retrospective/Core/Resources/Assets.xcassets/AccentColor.colorset/Contents.json, Retrospective/Retrospective/Core/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json, Retrospective/Retrospective/Core/Resources/Assets.xcassets/Contents.json, Retrospective/Retrospective/Core/Storage/AppStorageKey.swift, Retrospective/Retrospective/Core/Styles/TintedBorderlessStyle.swift, Retrospective/Retrospective/Models/Model.swift, Retrospective/Retrospective/RetrospectiveApp.swift, Retrospective/Retrospective/Utils/Extesnions/String+Extension.swift, Retrospective/Retrospective/Views/ContentView.swift, Retrospective/RetrospectiveTests/RetrospectiveTests.swift
=> feat: 프로젝트 초기 세팅 및 플레이스홀더 파일 생성, README.md 템플릿 작성

Retrospective/Core/Resources/AppColors.swift, Retrospective/Utils/Extesnions/Color+Extension.swift, Retrospective/Utils/Extesnions/UIColor+Extension.swift
close #7 
* 라이트 모드 및 다크 모드에 알맞은 색상으로 `Color` 인스턴스 생성을 도와주는 이니셜라이저를 새로 정의했습니다. 
* AppColors 파일에 우리 앱이 사용하는 공통 색상을 정의하세요~ 
```swift
// AppColors.swift
extension ShapeStyle where Self == Color {
/// 앱 메인 색상, 백그라운드 색상
static var example: Color {
Color(
light: Color(r: 111.0, g: 111.0, b: 111.0),
dark:  Color(r: 222.0, g: 222.0, b: 222.0)
)
}
}
```
=> feat: 라이트 및 다크 모드로 `Color`를 생성하는 이니셜라이저 확장 코드 구현

Retrospective/Core/CommonViews/TabBarView.swift, Retrospective/Core/CommonViews/Test1_View.swift, Retrospective/Core/CommonViews/Test2_View.swift, Retrospective/Core/CommonViews/Test3_View.swift, Retrospective/Core/CommonViews/Test4_View.swift, Retrospective/Views/ContentView.swift
> 탭바 구현 테스트 완료 했습니다.
> 탭 바에 있는 아이콘(홈,검색,통계,설정)  눌렀을때 연결되는 뷰 수정하고 싶으시면 제가 주석 처리해둔 부분에 만드신 뷰 넣어주시면 됩니다. 
=> Feat/탭바 구현

Retrospective/Core/CategoryButton/CategoryButton.swift
> CategoryButton의 변수&생성자 Binding 되게 하고, Preview 또한 수정하였습니다.
> 아직 Binding이 어색하고 잘몰라 변수와 생성자 구현을 맞게 한 건지, Preview에서도 맞게 구현을 하고 있는 건지 확인 부탁드립니다..!
=> Category Button 수정

Retrospective/Core/WritingView/Extensions/UIApplication+WritingView.swift, Retrospective/Core/WritingView/WritingView.swift
> 우선 전반적인 작성 뷰 UI 구현했습니다.
> CRUD, Navigationbar 버튼 기능, 카테고리 리스트&추가 버튼 기능을 추가 해야하는데 CRUD를 잘몰라 힘드네요.. 도와주시면 감사하겠습니다 😭
그리고 작성 뷰에서 수정, 삭제도 되게 하는 거면 작성 뷰를 재활용 한다는 의미인가요..?
=> WritingView구현

Retrospective/Core/WritingView/WritingView.swift, Retrospective/Views/ContentView.swift
> CRUD를 구현하려 노력해봤습니다..
(CRUD 구현을 해야하는 부분 주석처리함)
=> WritingView CRUD 구현 노력

Retrospective/Views/CategoryView/CategoryTest_View.swift, Retrospective/Views/CategoryView/CategoryView.swift, Retrospective/Views/ContentView.swift, Retrospective/Views/SettingView/SettingView.swift, Retrospective/Views/SettingView/settingView.swift
SettingView
SettingView구현완료 했습니다.
reenshot (Optional)
피드백 부탁드립니다.
=> settings view완료

Retrospective/Views/HomeView/Components/CardScrollView.swift, Retrospective/Views/HomeView/Components/CardScrollViewForPad.swift, Retrospective/Views/HomeView/Components/CardUIView.swift, Retrospective/Views/HomeView/Components/DayHeader.swift, Retrospective/Views/HomeView/Components/MonthHeader.swift, Retrospective/Views/HomeView/FilterSelectView.swift, Retrospective/Views/HomeView/HomeView.swift, Retrospective/Views/SearchView/SearchView.swift
UI 최적화 및 WritingView 연결.
FilterSelectView RoundedRectButton으로 수정.
FilterSelectView에서 카테고리 ㄱㄴㄷ 순으로 정렬되도록 수정.
=> UI최적화 및 WritingView 연결

Retrospective/Views/ContentView.swift, Retrospective/Views/WritingView/WritingView.swift
> 구현 마무리는 다 안됐지만 중간 커밋합니다.
> 유섭님 테스트 해보세요!
=> WritingView 구현 중간 커밋

Retrospective/Views/HomeView/Components/CardScrollView.swift, Retrospective/Views/HomeView/Components/CardScrollViewForPad.swift, Retrospective/Views/HomeView/Components/CardUIView.swift, Retrospective/Views/HomeView/Components/DayHeader.swift, Retrospective/Views/HomeView/Components/MonthHeader.swift, Retrospective/Views/HomeView/FilterSelectView.swift, Retrospective/Views/HomeView/HomeView.swift, Retrospective/Views/SearchView/SearchView.swift
각 뷰 여백 수정,
SearchView, HomeView, FilterView 스크롤 인디케이터 위치 조절.
SearchView 텍스트 필드 구성 수정.
- 스크롤 인디케이터 위치 조절. (SearchView도 동일.)
- SearchView 텍스트 필드 구성 수정.
=> 5/14 오후 회의 내용 수정.

Retrospective/Views/WritingView/WritingView.swift
> 적용이 잘 안되거나 구현하기 어려운 것들 빼고는 우선 다 구현했습니다.
> 라이트 모드
> 다크 모드
> 내일 나머지 구현하지 못한 것들 도와주시면 감사하겠습니다..😭
=> WritingView와 상세, 편집&삭제뷰 기능 추가

Retrospective/Views/HomeView/Components/CardUIView.swift, Retrospective/Views/HomeView/Components/DayHeader.swift, Retrospective/Views/HomeView/Components/MonthHeader.swift, Retrospective/Views/HomeView/HomeView.swift
=> feat: 홈 및 카테고리 등 일부 화면 UI 수정

Retrospective/Core/CommonViews/CategoryButton.swift, Retrospective/Core/CommonViews/CustomTextField.swift, Retrospective/Core/CommonViews/RoundedRectButton.swift, Retrospective/Core/Extensions/Color+RawRepresentable.swift, Retrospective/Core/Representable/UIViewRepresentableWrapper.swift, Retrospective/Core/Styles/CustomTextEditorStyle.swift, Retrospective/Core/Styles/TintedBorderlessStyle.swift, Retrospective/RetrospectiveApp.swift, Retrospective/Views/ContentView.swift, Retrospective/Views/WritingView/WritingView.swift
왜 되는지는 묻지 마세여ㅛ.. 
!!!! 그리고 옵셔널 강제 해제 구문 모두 안전하게 바꿔주세요 
Style 관련 코드 Core 쪽으로 이동
프리뷰가 아니라 시뮬레이터에서 테스트하셔야 정상 작동합니다
=> feat: 카테고리

Retrospective/Views/CategoryView/EmptyStateView.swift, Retrospective/Views/HomeView/Components/CategoryAndDateSortView.swift, Retrospective/Views/HomeView/Components/MonthHeader.swift, Retrospective/Views/HomeView/Components/ToggleSortOrder.swift, Retrospective/Views/HomeView/FilterSelectView.swift, Retrospective/Views/HomeView/HomeView.swift, Retrospective/Views/SearchView/SearchView.swift
1. SearchView
- 날짜 정렬 애니메이션 추가
-  검색방식 아이콘 수정
-  텍스트필드 공용 텍스트필드로 수정.
2. CategoryAndDateSortView
-  카테고리 + 날짜정렬 방식 보이는 부분 따로 뺌
-  카테고리 추가시 UI 틀어지는 부분 수정.
3. CategorySelectView
-  카테고리 선택 영역 최대로 넓힘.
4. 공용
- 간격 세부 조정.
- 동적 글꼴 사이즈 대응 (기본 Size UI 변경 X)
a. (.lineLimit + .minimumScaleFactor(0.8)) 활용.
b. height -> minHeight로 수정.
1. SearchView
2. HomeView 
시뮬레이터 상에서는 크래쉬 안나는 것 같습니다!
=> 5/15 오전 회의내용 수정 (HomeView, SearchView)

Retrospective/RetrospectiveApp.swift, Retrospective/Views/CategoryView/CategoryListView.swift, Retrospective/Views/CategoryView/CategoryView.swift, Retrospective/Views/ContentView.swift
탭바에 각자 작성하신 화면으로 이동 가능하게 수정했습니다~
=> feat: ContentsView 수정

Retrospective/Utils/Extesnions/TextEditor+Extension.swift, Retrospective/Utils/Extesnions/UIApplication+Extension.swift
> WritingView 관련 Extension 추가했습니다.
=> WritingView 관련 Extension 추가

Retrospective/Views/CategoryView/CategoryView.swift
> ex) #IssueNumber, #IssueNumber
> Please briefly describe what was worked on in this PR (Images can be attached).
=> 카테고리뷰 오류 해결

Retrospective/Models/Diary.swift
=> 시연 영상용 다이어리 데이터 추가.

Retrospective/Views/CategoryView/EditCategoryView.swift
1.텍스트필드 선택시 뷰올라가는 현상 해결
2.텍스트 필드에 최소 한글자는 작성하도록 알림창 생성
> Please briefly describe what was worked on in this PR (Images can be attached).
=> 카테고리 수정뷰 버그수정

Retrospective/Views/CategoryView/CategoryView.swift, Retrospective/Views/HomeView/HomeView.swift, Retrospective/Views/SearchView/SearchView.swift
=> feat: 소소한 UI 및 기능 수정

Retrospective/Views/ContentView.swift
> ex) #IssueNumber, #IssueNumber
> Please briefly describe what was worked on in this PR (Images can be attached).
=> feat: 소소한 UI 수정

Retrospective/Core/FloatingSheet/FloatingSheet.swift
> ex) #IssueNumber, #IssueNumber
> Please briefly describe what was worked on in this PR (Images can be attached).
=> feat: floatingSheeet 사이즈 수정
